name : CommandLock
main : kr.mocha.CommandLock
version : 1.1-SNAPSHOT
author : mocha
description : "Lock Commands!"
api : [1.0.0]

commands :
 commandlock :
  description : "Lock commands"
  usage : "/commandlock <add|del|list>"
  aliases : ["cmdlock"]